.. _user-docs:


|user-img| User Documentation
=============================

.. |user-img| image:: _static/user.png
	:height: 32px
	:align: middle
	
* :ref:`uftp-client` - the standalone UFTP client application 

.. toctree::
	:maxdepth: 5
	:caption: User Documentation
	:hidden:

	user-docs/uftp-client/uftpc-index



