.. _admin-docs:


Admin Documentation
===================

* :ref:`uftpd` - the UFTP file server 
* :ref:`authserver` - a set of services providing authentication for UFTP as well as data 
  sharing features
 

.. toctree::
	:maxdepth: 5
	:caption: Admin Documentation
	:hidden:

	admin-docs/uftpd/index
	admin-docs/authserver/index
