.. _admin-docs:


|admin-img| Admin Documentation
===============================

.. |admin-img| image:: _static/admin.png
	:height: 32px
	:align: middle

:ref:`uftpd`
	The UFTP file server.
	
:ref:`authserver`
	A set of services providing authentication for UFTP as well as data 
	sharing features.
 

.. toctree::
	:maxdepth: 5
	:caption: Admin Documentation
	:hidden:

	admin-docs/uftpd/index
	admin-docs/authserver/index
